### ISSUE TITLE
¿Qué necesitas para que funcione en *nix?

### ISSUE THREAD

**Issue by mautematico** [PolygonTechMX/CFDI#3]
¿Qué necesitas para que funcione en *nix?

**Comment by mautematico** [comment]
Sí.

Específicamente Debian GNU/Linux

**Comment by daviidmart** [comment]
Estoy trabajando en una versión en la que viene embebido openssl y libxml pero por lo pronto lo que puedes hacer es instalar localmente enviar el path en el constructor, tiene una propiedad llamada opensslDir o otra libxmlDir
